services:

    #
    # Commands
    #
    search_bundle.reset_index_command:
        class: Puntmig\Search\Command\ResetIndexCommand
        arguments:
            - "@puntmig_search.repository_bucket"
        tags:
            - { name: console.command }