services:

    #
    # Http clients
    #
    search_bundle.guzzle_client:
        class: Puntmig\Search\Http\GuzzleClient
        arguments:
            - "%search_bundle.endpoint"

    search_bundle.http_client:
        alias: search_bundle.guzzle_client