services:

    #
    # Adapters
    #
    search_bundle.http_repository:
        class: Puntmig\Search\Repository\HttpRepository
        arguments:
            - "@search_bundle.http_client"
        calls:
            - ["setKey", ["%search_bundle.api_key%"]]
