services:

    #
    # Aggregation Translator
    #
    puntmig_search.aggregation_translator:
        class: Puntmig\Search\Translator\AggregationTranslator
        arguments:
            - "@?translator"