services:

    #
    # Repositories
    #
    puntmig_search.url_builder_extension:
        class: Puntmig\Search\Twig\UrlBuilderExtension
        arguments:
            - "@puntmig_search.url_builder"
        tags:
            - { name: twig.extension }

    puntmig_search.aggregation_translation_extension:
        class: Puntmig\Search\Twig\AggregationTranslationExtension
        arguments:
            - "@puntmig_search.aggregation_translator"
        tags:
            - { name: twig.extension }

    puntmig_search.method_accessor:
        class: Puntmig\Search\Twig\MethodAccessorExtension
        tags:
            - { name: twig.extension }