services:

    #
    # Repositories
    #
    apisearch.url_builder_extension:
        class: Apisearch\Twig\UrlBuilderExtension
        arguments:
            - "@apisearch.url_builder"
        tags:
            - { name: twig.extension }

    apisearch.aggregation_translation_extension:
        class: Apisearch\Twig\AggregationTranslationExtension
        arguments:
            - "@apisearch.aggregation_translator"
        tags:
            - { name: twig.extension }

    apisearch.method_accessor:
        class: Apisearch\Twig\MethodAccessorExtension
        tags:
            - { name: twig.extension }