services:

    #
    # Repositories
    #
    search_bundle.url_builder_extension:
        class: Puntmig\Search\Twig\UrlBuilderExtension
        arguments:
            - "@search_bundle.url_builder"
        tags:
            - { name: twig.extension }

    search_bundle.aggregation_translation_extension:
        class: Puntmig\Search\Twig\AggregationTranslationExtension
        arguments:
            - "@search_bundle.aggregation_translator"
        tags:
            - { name: twig.extension }